### ISSUE TITLE
Latest additions and opts: api are not released in rubygems

### ISSUE THREAD

**Issue by sandersiim** [jesjos/active_record_upsert#104]
Latest rubygems.org version is 0.9.5 which doesn't contain the opts: API described in README of this repo, which is confusing. Can latest state be released to rubygems as well?

**Comment by olleolleolle** [comment]
https://github.com/jesjos/active_record_upsert/releases/tag/v0.11.1 was released after this was mentioned, so thanks for the reminder!

I will close this Issue.
