### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by jherdman** [jesjos/active_record_upsert#109]
On the off chance this isn't on your radar, would you mind doing a release? This library is presently a blocker on upgrading to Rails 6.1 for my team.

❤️

**Comment by olleolleolle** [comment]
Are you using the library? Is it a dependency you like? Do you want to join me in maintaining it?

**Comment by jherdman** [comment]
I'm not sure I'm a great candidate as I'm not familiar with the code. How can I can best help at this time?

**Comment by olleolleolle** [comment]
My suggestion: you learn to bump the version, write a release note, and "make the release", and we take it from there. Then you'll be able to assist this project with that careful once-every-6-months task.

Does this sound like you?

**Comment by jherdman** [comment]
Closed by #110
