### ISSUE TITLE
Upserting a record doesn't clear the "dirty" state

### ISSUE THREAD

**Issue by nickcampbell18** [jesjos/active_record_upsert#113]
When I create or update a record, I would expect it to clear the `changes` on the model:

```ruby
person = Person.create!(id: 1)
=> #<Person id: 1, ..>
person.changes
=> {}
```

This isn't the case with upserts, even after the record has been safely persisted:

```ruby
person = Person.new(id: 2)
person.upsert!
=> #<Person id: 2, ..>
person.changes
=> {"id"=>[nil, 2], "created_at"=>[nil, Tue, 20 Apr 2021 13:10:33.226426000 UTC +00:00], "updated_at"=>[nil, Tue, 20 Apr 2021 13:10:33.226426000 UTC +00:00]}
```

I noticed this when mixing upserted models with relations. Because Rails thinks the relation has changes, it attempts an update of that recently-upserted record. For example:

```ruby
# Organization.has_many :people
organization = Organization.first

person = Person.new(id: 2)
person.upsert!
organization.people << person
```
... this issues two queries:

```sql
INSERT INTO "people" ("id") VALUES ($1) ON CONFLICT ...
UPDATE "people" SET "id" = $1 WHERE "people"."id" IS NULL [["id", 2]]
```

(also the second query seems to apply the `WHERE` filter wrongly and will update zero records, so it isn't helpful here anyway).

Digging through the Rails source, I think we might need to also call the `changes_applied` method in the same way that `ActiveRecord::AttributeMethods::Dirty` [does it](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/attribute_methods/dirty.rb#L196). Or maybe I'm missing something else?

**Comment by olleolleolle** [comment]
@nickcampbell18 Cool analysis! Do you think you want to offer a PR with tests and a change for this behavior to better match your expectations?

**Comment by nickcampbell18** [comment]
I will try my best :+1:
