### ISSUE TITLE
Release version v0.11.0

### ISSUE THREAD

**Issue by nickcampbell18** [jesjos/active_record_upsert#124]
@olleolleolle could I trouble you please to release a new version (probably `v0.11.0` given #123)? This is the final dependency in my pile of Rails 7 upgrades 😄 

Let me know if I can do anything. I've noticed there isn't a CHANGELOG.md, I'd be happy to write one if you wanted.

**Comment by olleolleolle** [comment]
@nickcampbell18 if you have a proposed CHANGELOG note we can slap it onto the Release in GitHub (skipping a markdown file for now, perhaps if you feel like making one, but the most important thing is "what's in the current one?")

**Comment by nickcampbell18** [comment]
* Rails 7 compatibility
* Dropped support for Rails 5.0 and Rails 5.1
* Added official support for Ruby 3.0

**Comment by olleolleolle** [comment]
Released as v0.11.1, I really don't like the "Save Draft" creating a Git Tag for me, it should be inert until I say "please publish".

**Comment by nickcampbell18** [comment]
Thank you very much 🙏

**Comment by olleolleolle** [comment]
@nickcampbell18 You're an active user of this gem, right?

Would you like to join the maintenance team, and be able to release this gem?

**Comment by nickcampbell18** [comment]
Sure, that would be nice!
