### ISSUE TITLE
Ruby 3.1 support

### ISSUE THREAD

**Issue by gnumarcelo** [jesjos/active_record_upsert#135]
Hey guys, as we have this states in the docs:

 > Please note that Ruby 3.1 is not currently tested because it is incompatible with Rails 7.0.0, 6.1.4.4, 6.0.4.4 and 5.2.6 (https://github.com/rails/rails/issues/43998).
 
 And that Rails issue is currently fixed, I'm wondering if this gem is being tested/compatible with Ruby 3.1.
 
 ps.: Thanks for maintaining the project, by the way.

**Comment by olleolleolle** [comment]
Would you like to offer a PR adding 3.1 to the ci matrix and fix the README?
