### ISSUE TITLE
Rails 7.2: undefined methd rollback_active_record_state!

### ISSUE THREAD

**Issue by olleolleolle** [jesjos/active_record_upsert#140]
Ah, learning more about the next version of Rails here: the rails-main tests fail, and have warnings like

> NoMethodError:
>        undefined method `rollback_active_record_state!' for #<MyRecord id: 0, name: nil, wisdom: nil, created_at: nil, updated_at: nil>

No action needed. Merging this!

_Originally posted by @olleolleolle in https://github.com/jesjos/active_record_upsert/issues/139#issuecomment-1776541961_

**Comment by jgraichen** [comment]
This happens because the compatibility module is only included for specific Rails version (7.0, 7.1), which is fixed for Rails 7.2 in !144.

See https://github.com/jesjos/active_record_upsert/blob/main/lib/active_record_upsert.rb#L16.
