### ISSUE TITLE
why pg only?

### ISSUE THREAD

**Issue by BKSpurgeon** [jesjos/active_record_upsert#24]
Hi all

thank you for your gem. it is very interesting. i have two questions:

(i) why must the test db be upsert_test?

(ii) am curious why pg is a requisite: cannot other db be just as easily used?

chrs

Ben

**Comment by olleolleolle** [comment]
The PG-only is "we only needed PG".

**Comment by BKSpurgeon** [comment]
ok chrs. also why must the test db be named: upsert_test?

**Comment by olleolleolle** [comment]
It doesn't. Laziness. PRs welcome.

**Comment by BKSpurgeon** [comment]
thank you so much for answering my questions. this project definitely does look interesting.

rgds

Ben
