### ISSUE TITLE
Support Rails 5.1.1

### ISSUE THREAD

**Issue by ValentinTrinque** [jesjos/active_record_upsert#28]
I attempt to use your gem with a Rails 5.1.1 project, but failed at installation. Here is the error :

```
Bundler could not find compatible versions for gem "activerecord":
  In snapshot (Gemfile.lock):
    activerecord (= 5.1.1)

  In Gemfile:
    active_record_upsert (~> 0.6) was resolved to 0.6.1, which depends on
      activerecord (~> 5.0.0.beta4)

    rails (~> 5.1.0) was resolved to 5.1.1, which depends on
      activerecord (= 5.1.1)
```

What about supporting Rails 5.1.1 ?

**Comment by olleolleolle** [comment]
Can you try with current master?

**Comment by pocke** [comment]
Hi. I use Rails 5.1.2, and I had same issue.
I tried using this gem with master branch, it works well. 

Could you release this gem to rubygems.org?

**Comment by olleolleolle** [comment]
@pocke Thanks for the reminder and the reassurance.

v0.7.0 is now on RubyGems.
