### ISSUE TITLE
Support index expressions

### ISSUE THREAD

**Issue by marcgreenstock** [jesjos/active_record_upsert#31]
Hi, does/could this library support index expressions such as md5 indexes?

When the query is generated the columns in `upsert_keys` are wrapped in quotes:  

```ruby
class User < ApplicationBase
  upsert_keys ['md5(name)']
end
```

```sql
INSERT INTO "users" ("created_at", "updated_at", "name")
VALUES ($1, $2, $3)
ON CONFLICT ("md5(name)") DO UPDATE SET "updated_at" = $2
RETURNING *;
```

The index expression `md5(name)` should not be in quotes.

**Comment by olleolleolle** [comment]
The library does not have a maintainer, basically; but if you have PRs, go ahead and PR.

**Comment by marcgreenstock** [comment]
okay i'll see what I can come up with

**Comment by paulwalker** [comment]
additionally, in some cases it is necessary to name the constraint (as you do with partial unique indexes apparently. `ON CONFLICT ON CONSTRAINT <contraint_name>`

**Comment by olleolleolle** [comment]
@paulwalker The more you learn! Thanks for weighing in.
