### ISSUE TITLE
Support for inheriting upsert_keys

### ISSUE THREAD

**Issue by maxjacobson** [jesjos/active_record_upsert#44]
Hi there,

We've been using your library and really appreciate it. Thanks!

One hiccup we just encountered is that, when using single-table inheritance, the upsert keys are not inherited by the subclasses. For example:

```ruby
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

class Animal < ApplicationRecord
  upsert_keys [:owner_id, :type]
end

class Cat < Animal
end

2.times do |n|
  Animal.upsert(
    owner_id: 1,
    type: "Cat",
    name: "Fluffy #{n}",
  )
end
```

In the presence of a unique index on `owner_id` and `type` in the animals table, the above code block will raise an exception:

```
PG::UniqueViolation: ERROR: duplicate key value violates unique constraint
```

The issue, it seems, is that `Cat.upsert_keys` returns `nil` rather than `[:owner_id, :type]`, which leads to an `ON CONFLICT` clause which checks the primary key rather than our upsert keys:

https://github.com/jesjos/active_record_upsert/blob/fad3b92aa0ba9ed0ea32ed024a082be58987a103/lib/active_record_upsert/active_record/relation.rb#L6

What do you think about having the child classes inherit the upsert keys? We're happy to help make this change if it sounds good to you.

**Comment by jesjos** [comment]
Thanks for writing such a thoughtful issue! If you’d be prepared to submit a PR, that’d be super. 👍

**Comment by maxjacobson** [comment]
Hey, thanks!
