### ISSUE TITLE
Please publish a new version 🙏

### ISSUE THREAD

**Issue by vassilevsky** [jesjos/active_record_upsert#46]
Hello. Thank you for this gem! It's a long awaited feature!

We wanted to use all the new functionality in our project. But when we added the gem, it didn't have all of it. There have been quite a few commits since the last release.

Could you publish another release with all the new code?

Thanks!

**Comment by olleolleolle** [comment]
@vassilevsky Thanks for the kind words. In return, here's an extremely terse release note:

https://github.com/jesjos/active_record_upsert/releases/tag/v0.7.1

**Comment by vassilevsky** [comment]
Thanks, Jesper! 👍

**Comment by olleolleolle** [comment]
@jesjos Thanks!
