### ISSUE TITLE
Support pg version 1.0.0

### ISSUE THREAD

**Issue by gaffneyc** [jesjos/active_record_upsert#47]
The version constraint for the dependency on `pg` may be too strict and isn't allowing 1.0+ of the pg gem. Would be great to make sure version 1.0.0 is supported and relax the version constraint.

**Comment by olleolleolle** [comment]
Care to make the check?

**Comment by gaffneyc** [comment]
Sure, I can take a look

**Comment by olleolleolle** [comment]
20+ days ago this was committed to Rails' repo:

https://github.com/rails/rails/commit/f820dc2dea3775f6c05c5ca77631ac27a9d3c954#diff-d7ae9a835adce5aead1bf757f121e359

**Comment by gaffneyc** [comment]
After a quick check it appears that ActiveRecord 5.1.4 (and probably older) have a version constraint hard coded for `gem "pg", "~> 0.18"`

Edit: Just saw that and this issue: https://github.com/rails/rails/pull/31671

**Comment by gaffneyc** [comment]
As far as ActiveRecord goes, it looks like pg 1.0 won't be supported until 5.0.7, 5.1.5, and 5.2.0

**Comment by olleolleolle** [comment]
v0.7.2 has been released.

**Comment by gaffneyc** [comment]
Thanks! :+1:
