### ISSUE TITLE
Does not work with associations

### ISSUE THREAD

**Issue by abinoda** [jesjos/active_record_upsert#69]
This works:
```ruby
MyModel.upsert!(
  uuid: 'foobar',
  category_id: @category.id,
  color_id: @color.id
)
```

This does not work:
```ruby
MyModel.upsert!(
  uuid: 'foobar',
  category: @category,
  color: @color
)
```

**Comment by abinoda** [comment]
@jesjos @olleolleolle  In the second example, the `color` will not be updated in the database and no warnings or errors are thrown. This means that a lot of my `upsert!` calls are not doing what I thought they were doing 😢

**Comment by abinoda** [comment]
@jesjos Can you confirm that what I reported is the current behavior?

For now I've just rewritten my code so I always refer to the database column names versus association names. This seems like an OK solution but I think this library should then throw an exception when trying to refer to an association name like `ERROR: unrecognized column :category - did you mean :category_id`.

What do you think?

**Comment by jesjos** [comment]
I can't confirm it right now, but I'm pretty sure it behaves the way you describe. I think we should be able to solve it by calling `#to_param` or something similar on the values to be inserted.

**Comment by abinoda** [comment]
@jesjos That makes sense. I don't think it needs to support calling associations if it adds complexity. But if its easy to do that'd be great

**Comment by jesjos** [comment]
Ah, it wasn't that easy, of course. `#to_param` will dumb down everything to a string. I'm trying to sift through the "normal" active record code to see how they handle this.

**Comment by jesjos** [comment]
We might be able to do something like:

```
values.transform_values! { |v| v.respond_to?(:to_key) ? v.to_key : v }
```

**Comment by jesjos** [comment]
I think we're basically missing something like the call to `assign_attributes` that is done in (for example) `#update`:

https://github.com/rails/rails/blob/master/activerecord/lib/active_record/persistence.rb#L427
