### ISSUE TITLE
bulk processing and define fields with upsert instead of class

### ISSUE THREAD

**Issue by goravbhootra** [jesjos/active_record_upsert#73]
Hi,

We are working on doing bulk data import and are looking for a library supporting upsert. Trying to understand how we can:

1. Upsert bulk array of hashes

1. Define the `conflict clause` while doing `.upsert` rather than defining it it class. Different combination of data needs to figure out duplicates on different keys.

Thanks in advance.

**Comment by tjwallace** [comment]
Try https://github.com/zdennis/activerecord-import

**Comment by jesjos** [comment]
PR welcome, but the maintainers won't develop this functionality.
