### ISSUE TITLE
Custom `upsert_keys` per call to `upsert`

### ISSUE THREAD

**Issue by dounan** [jesjos/active_record_upsert#74]
We have a `foo` table that has two unique indices:
```rb
t.index ["a", "b", "c"], unique: true, using: :btree
t.index ["a", "b"], unique: true, where: "(c IS NULL)", using: :btree
```

In our model, we specify the `upsert_keys` to cover the first unique index as follows:
```rb
class Foo < ActiveRecord::Base
  upsert_keys [:a, :b, :c]
end
```

However, whenever we do an `upsert` on a record that has a `nil` value for `c`, we run into duplicate key errors from the second unique index.

Is there any way in the current library to set the `index_column_names` and `index_expression` per `upsert` call?

For example, something like:

```rb
if foo.c.nil?
  foo.upsert(upsert_keys: [:a, :b], :upsert_options: {where: "c IS NULL"})
else
  foo.upsert(upsert_keys: [:a, :b, :c])
end
```

**Comment by hahuang65** [comment]
Would like to bump this, as I'm requiring this feature for something I'm working on as well.

It's not uncommon to have different upsert clauses.

**Comment by olleolleolle** [comment]
Pull Requests are welcome!

**Comment by hahuang65** [comment]
@olleolleolle just added one 👍
