### ISSUE TITLE
Explain difference between this library and Rails 6

### ISSUE THREAD

**Issue by olleolleolle** [jesjos/active_record_upsert#95]
You probably _can_ use the built-in Rails methods `upsert_all` and `upsert` in Rails 6.

- https://medium.com/@retrorubies/upcoming-rails-6-bulk-insert-upsert-feature-2d642419557d
- https://github.com/rails/rails/pull/35631

Todo:

- Link to https://medium.com/@retrorubies/upcoming-rails-6-bulk-insert-upsert-feature-2d642419557d and https://github.com/rails/rails/pull/35631 prominently in the docs

**Comment by jesjos** [comment]
I think we can say this was covered in #131
